version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
    - ./.postgres-data:/var/lib/postgresql/data
    - ./scripts/001-create-databases.sql:/docker-entrypoint-initdb.d/001-create-databases.sql

